mxenabled/path-core

build.gradle
gradle.properties
jitpack.yml

Make changes needed to publish to jitpack
* Create jitpack.yml
* Set jdk
* Remove install task alias
@SandhyaBhatia

Configure jitpack publishing

---

gradle.properties
jitpack.yml

* Add gradle.properties to set jvm settings
* Remove gradle.properties in jitpack.yml

Add gradle.properties

---

.github/workflows/gradle.yml
README.md

Fix github actions

---

.github/ISSUE_TEMPLATE/SECURITY_ISSUE.yml
build.gradle

* Add path to assignee list
* Remove required validation from CVE
@sskousen @mxenabled/path

Adjust security issue template

---

build.gradle

Bump version to 0.0.2

---

common/src/main/java/com/mx/common/connect/Response.java
common/src/test/groovy/com/mx/common/connect/ResponseTest.groovy
gateway/src/test/groovy/com/mx/path/gateway/net/ResponseTest.groovy

BREAKING CHANGE: Changes exception thrown on unknown exception
* Unknown exception will result in an AccessorSystemException

fix!: update Response#throwException to

---

upgrades/v1/README.md

Updates v1 upgrade notes to point to final locations.

docs: finalize v1 upgrade notes

---

README.md

Documenting release and versioning strategy.

docs: document release procedures

---

README.md

docs: link to MX Path SDK documentation

---

.github/workflows/commits.yml
.gitignore
.husky/commit-msg
README.md
bin/reset
bin/setup
build.gradle
commitlint.config.js
package-lock.json
package.json

Add husky with commitizen, commitlint

build: configure husky and conventional commit tooling

---

common/src/main/java/com/mx/common/exception/PathRequestException.java
common/src/main/java/com/mx/common/messaging/MessageError.java

Change parent of MessageError to PathRequestException. This was missed in the exception rework. Should not impact current usage.

fix: change MessageError parent to PathRequestException

---

.github/src_filters.yml
.github/workflows/gradle.yml
.github/workflows/release.yml

* Disable scan stage unless src or build-related files changed
* Remove "v" from release tags

Disable scanning on doc changes

---

common/src/main/java/com/mx/common/accessors/BadRequestException.java
common/src/main/java/com/mx/common/accessors/RequestValidationException.java
common/src/main/java/com/mx/common/exception/PathRequestException.java

This adds two new AccessorUserExcpetions to be used when requests either have invalid data, or are malformed.

Adding two new AccessorUserExceptions

---

.github/workflows/publish.yml
.gitignore
build.gradle
common/gradle.lockfile
context/gradle.lockfile
gateway-generator/gradle.lockfile
gateway/gradle.lockfile
http/gradle.lockfile
messaging/gradle.lockfile
settings.gradle
testing/gradle.lockfile
utilities/gradle.lockfile

feat: add artifact signing

---

.github/workflows/publish.yml
.github/workflows/release.yml

Calling publish from release action using outputs from release-please action.

build(actions): fix broken publish github action

---

common/src/main/java/com/mx/common/accessors/PathResponseStatus.java
common/src/main/java/com/mx/common/accessors/UpstreamSystemMaintenance.java
common/src/main/java/com/mx/common/accessors/UpstreamSystemUnavailable.java
common/src/main/java/com/mx/common/exception/PathRequestException.java
common/src/main/java/com/mx/common/http/HttpStatus.java

Adding UpstreamSystemUnavailable with accompanying documentation.

fix: add UpstreamSystemUnavailable exception

---

README.md
build.gradle

* Remove reference to jitpack
* Add link and badge for to Maven Central
* Clean up gradle style
* Fix gateway generator include example
* Remove unneeded jitpack repository from build.gradle

docs: cleanup readme

---

.github/workflows/ci.yml
.github/workflows/publish.yml
.github/workflows/release.yml

Use action scripts in path-tools for CI.

build(actions): use path-tools actions

---

common/src/main/java/com/mx/common/configuration/ConfigurationField.java

Adding some enhancements to help with scaffolding.
* Add placeholder field to ConfigurationField annotation

feat: add placeholder field to ConfigurationField annotation

---

common/src/main/java/com/mx/common/messaging/RemoteException.java
messaging/src/main/java/com/mx/path/api/connect/messaging/MessageErrorThrowableSerializer.java
messaging/src/test/groovy/com/mx/path/api/connect/messaging/MessageErrorThrowableSerializerTest.groovy

This change will return an AccessorUserException if the response in messaging is of an unknown _Type.

fix: return a known exception

---

common/src/main/java/com/mx/common/configuration/ConfigurationField.java
common/src/main/java/com/mx/common/configuration/ConfigurationSerializer.java
common/src/test/groovy/com/mx/common/configuration/ConfigurationSerializerTest.groovy
common/src/test/java/com/mx/testing/serialization/ConfigurationWithSecrets.java

* Add secret field to ConfigurationField annotation
* Add serializer that masks secret fields

Add safe configuration object serializer

---

common/src/main/java/com/mx/common/configuration/ConfigurationSerializer.java
common/src/test/groovy/com/mx/common/configuration/ConfigurationSerializerTest.groovy
common/src/test/java/com/mx/testing/serialization/ConfigurationWithSecrets.java

* Adds support for ConfigurationField.secret on lists.

Support ConfigurationField.secret lists

---

gateway/src/main/java/com/mx/path/gateway/configuration/ConfigurationBinder.java

* Uses ConfigurationSerializer to keep secrets masked.

Log configurations after binding

---

gateway/src/main/java/com/mx/path/gateway/configuration/ConfigurationBinder.java

log configurations after binding with debug level. We will keep it this way until we have configuration objects with sensitive values annotated correctly with `secret = true`

Log configurations after binding with debug level

---

common/src/main/java/com/mx/common/exception/ExceptionContext.java
context/src/main/java/com/mx/path/model/context/facility/Facilities.java
context/src/test/groovy/com/mx/path/model/context/facilities/FacilitiesTest.groovy
gateway/src/main/java/com/mx/path/gateway/configuration/Configurator.java
messaging/src/test/groovy/com/mx/path/api/connect/messaging/FacilityMessageBrokerSupplierTest.groovy
messaging/src/test/groovy/com/mx/path/api/connect/messaging/remote/RemoteServiceTest.groovy

Move Spring exception reporter and introduce new, gateway-configurable honeybadger exception reporter. Also adding additional information to the reported context fields.

feat: add exception reporter facility

---

common/src/main/java/com/mx/common/lang/TriConsumer.java
gateway/src/main/java/com/mx/path/gateway/configuration/Configurator.java
gateway/src/main/java/com/mx/path/gateway/configuration/ConfiguratorObserver.java
gateway/src/test/groovy/com/mx/path/gateway/configuration/ConfiguratorObserverTest.groovy
gateway/src/test/groovy/com/mx/path/gateway/configuration/ConfiguratorTest.groovy
gateway/src/test/java/com/mx/testing/accessors/proxy/BaseAccessorProxy.java
gateway/src/test/java/com/mx/testing/accessors/proxy/id/IdBaseAccessorProxy.java
gateway/src/test/java/com/mx/testing/accessors/proxy/id/IdBaseAccessorProxySingleton.java
gateway/src/test/java/com/mx/testing/gateway/BaseGateway.java
gateway/src/test/java/com/mx/testing/gateway/BaseGatewayConfigurator.java
gateway/src/test/java/com/mx/testing/gateway/TestAccountGateway.java
gateway/src/test/java/com/mx/testing/gateway/TestGateway.java
gateway/src/test/java/com/mx/testing/gateway/TestIdGateway.java

New configurator observer that can be used to react to gateway construction events.

feat: add configurator observer

---

common/src/main/java/com/mx/common/lang/TriConsumer.java
gateway/src/main/java/com/mx/path/gateway/configuration/ConfiguratorObserver.java

* Fix typos in TriConsumer javadocs
* Tighten up ConfiguratorObserver types

Configurator events cleanup

---

gateway/src/main/java/com/mx/path/gateway/configuration/Configurable.java
gateway/src/main/java/com/mx/path/gateway/configuration/ConfigurationBinder.java
gateway/src/main/java/com/mx/path/gateway/configuration/GatewayObjectConfigurator.java
gateway/src/test/groovy/com/mx/path/gateway/configuration/ConfigurationBinderTest.groovy
gateway/src/test/groovy/com/mx/path/gateway/configuration/GatewayObjectConfiguratorTest.groovy
gateway/src/test/java/com/mx/testing/MessageBrokerImpl.java
gateway/src/test/java/com/mx/testing/binding/BasicConfigurationObj.java
gateway/src/test/java/com/mx/testing/binding/BehaviorWithClientIDAndConfiguration.java
gateway/src/test/java/com/mx/testing/binding/BindedConfigGatewayService.java

Add interface that can be implemented on Configurations and GatewayObjects (Facilities, GatewayBehaviors, GatewayServices) to provide custom, instance code.

feat: configuration and gateway object configuration hooks

---

messaging/src/main/java/com/mx/path/api/connect/messaging/remote/RemoteService.java

Moving the `withTracing` scope up in `dispatch` method so that error handling will have tracing information from the request attached to it.
@RyanJones08

fix: move RemoteService dispatch tracing scope up so errors have tracing info

---

common/src/main/java/com/mx/common/exception/PathRequestException.java
common/src/main/java/com/mx/common/exception/PathRequestExceptionWrapper.java

See javadocs for details. This exception is defined in behaviors and is needed elsewhere.

feat: add new PathRequestExceptionWrapper

---

gateway/src/main/java/com/mx/path/gateway/configuration/Configurator.java
gateway/src/main/java/com/mx/path/gateway/configuration/ConfiguratorObserver.java
gateway/src/test/groovy/com/mx/path/gateway/configuration/ConfiguratorObserverTest.groovy
gateway/src/test/groovy/com/mx/path/gateway/configuration/ConfiguratorTest.groovy
gateway/src/test/java/com/mx/testing/binding/TestCacheStore.java

* Add new gateway configurator event, ClientFacilitiesInitialized
* Change visibility of event classes to public
* Reorder ConfiguratorObserver for clarity

feat(gateway): add client facilities initialized event to configurator

---

common/src/main/java/com/mx/path/core/common/accessor/AccessorSystemException.java
common/src/main/java/com/mx/path/core/common/accessor/AccessorUserException.java
common/src/main/java/com/mx/path/core/common/accessor/BadRequestException.java
common/src/main/java/com/mx/path/core/common/accessor/RequestValidationException.java
common/src/main/java/com/mx/path/core/common/accessor/ResourceNotFoundException.java
common/src/main/java/com/mx/path/core/common/accessor/UpstreamSystemMaintenance.java
common/src/main/java/com/mx/path/core/common/accessor/UpstreamSystemUnavailable.java
common/src/main/java/com/mx/path/core/common/connect/MisConfiguredFilterChainException.java
common/src/main/java/com/mx/path/core/common/connect/Request.java
common/src/main/java/com/mx/path/core/common/connect/Response.java
common/src/main/java/com/mx/path/core/common/connect/ResponseProcessingException.java
common/src/main/java/com/mx/path/core/common/exception/PathRequestException.java
common/src/test/groovy/com/mx/path/core/common/connect/ResponseTest.groovy
gateway/src/test/groovy/com/mx/path/gateway/util/LoggingExceptionFormatterTest.groovy
http/src/main/java/com/mx/path/connect/http/HttpRequest.java
upgrades/v2/README.md

Minor tweaks to AccessorUserException to clarify its correct use.

Correct constructors and make abstract

---

common/src/main/java/com/mx/path/core/common/process/FaultTolerantExecutor.java

This simplifies and allows us to bubble up actual exceptions from fault-tolerant executions.

feat!: add throws to FaultTolerantExecutor.submit()

---

common/src/main/java/com/mx/path/core/common/reflection/Annotations.java
common/src/test/groovy/com/mx/path/core/common/reflection/AnnotationsTest.groovy
common/src/test/java/com/mx/testing/WithAnnotations.java
common/src/test/java/com/mx/testing/WithAnnotationsBase.java
common/src/test/java/com/mx/testing/WithAnnotationsBaseBase.java
gateway/src/main/java/com/mx/path/gateway/configuration/ConfigurationBinder.java

This also renames and deprecates fieldsWithAnnotations for clarity

fix: making Annotations.fieldsAndAnnotations respect inheritance

---

common/src/main/java/com/mx/path/core/common/configuration/package-info.java
common/src/main/java/com/mx/path/core/common/reflection/Fields.java
common/src/test/groovy/com/mx/path/core/common/reflection/FieldsTest.groovy

Add configuration binding support for Class<?>

feat: add support for Class binding

---

common/src/main/java/com/mx/path/core/common/configuration/package-info.java
common/src/main/java/com/mx/path/core/common/reflection/Fields.java
common/src/test/groovy/com/mx/path/core/common/reflection/FieldsTest.groovy

* Cleanup (alphabetize and standardize error messages) Fields class and it's tests.
* Cleanup configuration package-info javadocs

refactor: cleanup fields class and tests

---

context/src/main/java/com/mx/path/core/context/ResponseContext.java
context/src/test/groovy/com/mx/path/core/context/ResponseContextTest.groovy

Add ResponseContext with response header support.

feat: add response status

---

context/src/main/java/com/mx/path/core/context/RequestContext.java
context/src/main/java/com/mx/path/core/context/UpstreamRequestConfiguration.java
context/src/main/java/com/mx/path/core/context/UpstreamRequestProcessor.java
context/src/test/groovy/com/mx/path/core/context/RequestContextTest.groovy
context/src/test/groovy/com/mx/path/core/context/UpstreamRequestConfigurationTest.groovy
context/src/test/groovy/com/mx/path/core/context/UpstreamRequestProcessorTest.groovy
gateway/src/main/java/com/mx/path/gateway/configuration/AccessorStackConfigurator.java
gateway/src/main/java/com/mx/path/gateway/connect/filter/UpstreamRequestProcessorFilter.java
gateway/src/test/groovy/com/mx/path/gateway/connect/filter/UpstreamRequestProcessorFilterTest.groovy

Add upstream request processing hooks and configurations to RequestContext.

feat: add upstream request processing

---

common/src/main/java/com/mx/path/core/common/serialization/ConfigurationTypeAdapter.java
common/src/main/java/com/mx/path/core/common/serialization/PatternTypeAdapter.java
common/src/main/java/com/mx/path/core/common/serialization/ZoneIdTypeAdapter.java

Add type adapters so complex types serialize correctly for configuration binding logging.

fix(configuration): add type adapters for complex configuration types

---

common/src/main/java/com/mx/path/core/common/serialization/DurationTypeAdapter.java
common/src/main/java/com/mx/path/core/common/serialization/PatternTypeAdapter.java
common/src/test/groovy/com/mx/path/core/common/serialization/DurationTypeAdapterTest.groovy
common/src/test/groovy/com/mx/path/core/common/serialization/PatternTypeAdapterTest.groovy

Implement missing deserialization for Duration and Pattern. Add some targeted tests as well.

Complete type adapters

---

common/src/main/java/com/mx/path/core/common/serialization/LocalDateTimeTypeAdapter.java
common/src/main/java/com/mx/path/core/common/serialization/LocalDateTypeAdapter.java
common/src/main/java/com/mx/path/core/common/serialization/OffsetDateTimeTypeAdapter.java
common/src/main/java/com/mx/path/core/common/serialization/ZonedDateTimeTypeAdapter.java
common/src/test/groovy/com/mx/path/core/common/serialization/LocalDateTimeTypeAdapterTest.groovy
common/src/test/groovy/com/mx/path/core/common/serialization/LocalDateTypeAdapterTest.groovy
common/src/test/groovy/com/mx/path/core/common/serialization/OffsetDateTimeTypeAdapterTest.groovy
common/src/test/groovy/com/mx/path/core/common/serialization/ZonedDateTimeTypeAdapterTest.groovy

Fix incorrect null check in date/time type adapter deserialization.

fix: handle nulls in Date/Time deserialization

---

build.gradle
common/build.gradle
common/gradle.lockfile
common/src/main/java/com/mx/path/core/common/connect/Request.java
common/src/main/java/com/mx/path/core/common/connect/UpstreamSystemUnavailableAfterRetries.java
common/src/test/groovy/com/mx/path/core/common/connect/RequestTest.groovy
common/src/test/java/com/mx/testing/connect/TestRequest.java
context/gradle.lockfile
gateway-generator/gradle.lockfile
gateway/gradle.lockfile
gateway/src/test/groovy/com/mx/path/gateway/connect/filter/ErrorHandlerFilterTest.groovy
gateway/src/test/java/com/mx/testing/RequestImpl.java
http/gradle.lockfile
http/src/main/java/com/mx/path/connect/http/HttpRequest.java
messaging/gradle.lockfile
test-gateway-generator/gradle.lockfile
test-gateways/gradle.lockfile
test-models/gradle.lockfile
testing/gradle.lockfile
testing/src/test/java/com/mx/testing/TestConnection.java

Adding support for Request retries using guava-retrying -> https://github.com/rholder/guava-retrying.

Add support for request retries

---

gateway/src/main/java/com/mx/path/gateway/util/UpstreamLogger.java

Logs `login` to logs for troubleshooting failed authentication
Fixes https://mxcom.atlassian.net/browse/MC-826
No changes to API
No impact to downstream consumer

feat: add login to logs for troubleshooting failed authentication

---

test-gateways/src/test/groovy/com/mx/gateway/GatewayMethodSpec.groovy

Clean up gateway method specs per suggestion.

test: clean up gateway method specs

---

http/src/main/java/com/mx/path/connect/http/HttpClientFilter.java

Set the Cookie spec to standard to fix an issue with FHB and invalid expires attribute

fix: Set Cookie Spec

---

common/src/main/java/com/mx/path/core/common/request/Feature.java
http/src/test/groovy/com/mx/path/api/connect/http/HttpAccessorConnectionTest.groovy

Adding new feature to support `products`
Feature.java
This shouldn't impact downstream consumers because it is a new implementation
No test needed

feat: adding products feature

---

gateway/src/main/java/com/mx/path/gateway/util/UpstreamLogger.java
gateway/src/test/groovy/com/mx/path/gateway/util/UpstreamLoggerTest.groovy

Renaming and duplicating some log fields so they line up with other mobile logs.

fix: tweak upstream log fields for better log viewing

---

gateway/src/main/java/com/mx/path/gateway/configuration/AccessorStackConfigurator.java
gateway/src/main/java/com/mx/path/gateway/configuration/ConnectionBinder.java
gateway/src/main/java/com/mx/path/gateway/configuration/GatewayObjectConfigurator.java

Enables use of Connection notation on gateway objects constructors (e.g. Behaviors, Facilities, etc).
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

feat: add connection builder for gateway objects

---

common/src/main/java/com/mx/path/core/common/security/LogValueMasker.java
common/src/main/java/com/mx/path/core/common/security/LogValueRegex.java
common/src/test/groovy/com/mx/path/core/common/security/LogValueRegexTest.groovy

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes # (issue)
Please include a description of any new or modified publicly available classes and/or methods (if applicable).
Please include a description of how downstream consumers will be affected (breaking changes, bug fixes, internal behavior modification, etc.). If this PR introduces breaking changes please list out each of the breaking changes, as well as steps for migrating incompatible code.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

fix: mc-3689 - centralize some log masker regex strings
