mxenabled/path-core

common/src/main/java/com/mx/path/gateway/util/MdxApiException.java
common/src/test/groovy/com/mx/path/gateway/util/MdxApiExceptionTest.groovy

This addresses serialization issue causing messaging responses to not send.

fix: remove redundant code field from MdxApiException

---

.github/workflows/ci.yml
.github/workflows/release.yml
common/src/main/java/com/mx/common/accessors/PathResponseStatus.java
common/src/main/java/com/mx/common/http/HttpStatus.java
common/src/test/groovy/com/mx/common/http/HttpStatusTest.groovy

Add support for 531 Upstream Service Unavailable http status.
This new status is not an officially-support HTTP status. If the status is unacceptable, then a filter may be needed to change it to something standard. The inclusion helps provide trouble-shooting information to the caller about why a valid call failed.

fix: add service unavailable http status

---

common/src/main/java/com/mx/common/configuration/package-info.java
common/src/main/java/com/mx/common/reflection/Fields.java
common/src/test/groovy/com/mx/common/reflection/FieldsTest.groovy

Configuration POJOs can be defined as Enumerations. The values, provided as strings will be coerced into the defined type.

Add support for enum configuration bindings

---

common/src/main/java/com/mx/common/serialization/ConfigurationTypeAdapter.java
common/src/main/java/com/mx/common/serialization/DurationTypeAdapter.java
common/src/test/groovy/com/mx/common/serialization/ConfigurationTypeAdapterTest.groovy
common/src/test/groovy/com/mx/testing/Account.java
common/src/test/java/com/mx/testing/serialization/ConfigurationWithDuration.java
gateway/src/main/java/com/mx/path/gateway/configuration/ConfigurationBinder.java

When serializing configurations, Durations fail when null, also need to use a TypeAdapter for durations so that serialization will work in JDK 17.
Cleanup: Also renaming ConfigurationSerializer and moving into serialization package.

fix: duration serialization fail on null

---

testing/src/main/java/com/mx/path/testing/request/RequestMatcher.java

Adding `withMatcher` since `with` conflicts with a global groovy function.

test: add withMatcher to RequestMatcher

---

common/src/main/java/com/mx/common/connect/ServiceUnavailableException.java
common/src/main/java/com/mx/common/connect/TimeoutException.java
common/src/main/java/com/mx/common/connect/TooManyRequestsException.java

Updating statuses on connection exceptions to bring them in line with upstream system failure standards. Should respond with a 531. Setting code to previous status codes to help provide more information about the failure.
Updating statuses on connection exceptions to bring them in line with upstream system failure standards. Should respond with a 531. Setting code to previous status codes to help provide more information about the failure.

fix: update connect exception statuses and set codes

---

gateway/src/main/java/com/mx/path/gateway/connect/filters/HttpClientConnectException.java
gateway/src/main/java/com/mx/path/gateway/net/executors/HttpClientExecutor.java
http/src/main/java/com/mx/path/api/connect/http/HttpClientFilter.java

Introduce new exception type and catch more targeted exceptions in `HttpClientFilter` and `HttpClientExecutor`

fix: handle more specific HttpClient exceptions

---

gateway/src/main/java/com/mx/path/gateway/configuration/ConfigurationState.java

I think this was an oversight. We may need to get access to the current configuration state from outside of the configurator context.

fix: expose the current ConfigurationState

---

build.gradle
gateway-generator/src/main/java/com/mx/path/api/AccessorProxyGenerator.java
gateway-generator/src/main/java/com/mx/path/api/remote/RemoteAccessorGenerator.java

This is only a backward compatibility tweak. This code will be reworked in v2 to remove the hard-coded package path and calculate the package path given inputs.
Tested this with new and old MDX package paths to ensure no impact.

fix: allow gateway generator to support accessor and accessors package

---

build.gradle
gateway/src/main/java/com/mx/path/gateway/configuration/ConfigurationBinder.java
gateway/src/test/groovy/com/mx/path/gateway/configuration/ConfigurationBinderTest.groovy
gateway/src/test/java/com/mx/testing/binding/ConfigurationWithChangedFieldName.java
gateway/src/test/java/com/mx/testing/binding/ConfigurationWithChangedFieldNameBlank.java

Use the annotation value instead of the field name to conduct field validation

fix: issue 1436

---

upgrades/v2/core-2-upgrade.sh

Adding easy ServiceIdentifier.Session migration to v2 upgrade script.

docs: add ServiceIdentifier.Session to v2 upgrade script

---

http/src/main/java/com/mx/path/connect/http/HttpClientFilter.java
http/src/main/java/com/mx/path/connect/http/certificate/FieldSettingsValidationError.java
http/src/main/java/com/mx/path/connect/http/certificate/KeyStoreBuilder.java
http/src/main/java/com/mx/path/connect/http/certificate/LoadedKeystore.java
http/src/main/java/com/mx/path/connect/http/certificate/MutualAuthProvider.java
http/src/main/java/com/mx/path/connect/http/certificate/MutualAuthProviderFactory.java
http/src/main/java/com/mx/path/connect/http/certificate/MutualAuthProviderKeystore.java
http/src/test/groovy/com/mx/path/api/connect/http/certificate/LoadedKeystoreTest.groovy
http/src/test/groovy/com/mx/path/api/connect/http/certificate/MutualAuthProviderFactoryTest.groovy
upgrades/v2/core-2-upgrade.sh

Renaming com.mx.path.api.connect.http.certificates to com.mx.path.api.connect.http.certificate (missed it in previous reorganization)

Rename certificates package

---

common/src/main/java/com/mx/path/core/common/connect/Response.java

JSON deserialization is too specific to the upstream service. Marking deprecated.

Deprecate response json

---

common/src/main/java/com/mx/path/core/common/collection/Order.java
common/src/main/java/com/mx/path/core/common/collection/OrderComparator.java
common/src/main/java/com/mx/path/core/common/collection/Ordered.java
common/src/test/groovy/com/mx/path/core/common/collection/OrderComparatorTest.groovy
common/src/test/java/com/mx/testing/collection/OrderedFirst.java
common/src/test/java/com/mx/testing/collection/OrderedIndifferent1.java
common/src/test/java/com/mx/testing/collection/OrderedIndifferent2.java
common/src/test/java/com/mx/testing/collection/OrderedLast.java
common/src/test/java/com/mx/testing/collection/OrderedUnspecified.java
gateway/src/main/java/com/mx/path/gateway/configuration/BehaviorStackConfigurator.java

Adding a collection ordering annotation (`Order`) and comparator (`OrderComparator`). These are general purpose, but are being added to support behavior ordering.

feat: collection ordering annotation and comparator

---

gateway/src/main/java/com/mx/path/gateway/configuration/ConfigurationBinder.java
gateway/src/test/groovy/com/mx/path/gateway/configuration/ConfigurationBinderTest.groovy

If an @Configuration annotation is provided in the constructor of any gateway object, the `configurations` hash is expected even if all defaults are desired. A null reference exception is thrown if no `configurations` node if given. This makes the `configurations` node optional. The validation will still occur, so if a required value is missing, initialization will still fail.

fix: handle null ObjectMap in ConfigurationBinder

---

build.gradle
common/src/main/java/com/mx/path/core/common/connect/AccessorConnectionSettings.java
common/src/main/java/com/mx/path/core/common/connect/ConnectionSettings.java
common/src/test/groovy/com/mx/path/core/common/connect/AccessorConnectionSettingsTest.groovy
common/src/test/groovy/com/mx/path/core/common/connect/RequestTest.groovy
http/src/main/java/com/mx/path/connect/http/certificate/MutualAuthProviderFactory.java

This replaces the use of `AccessorConnectionSettings.hashcode` with more explicit `mutualAuthProviderHashcode`. This maintains the ability to override `ConnectionSettings` uniqueness for caching of mutual auth settings, but fixes the lack of transparency of solution that used equals/hashcode.
BREAKING CHANGE:
This adds a method to `ConnectionSettings` interface.

fix(mutual_auth)!: replace use of ConnectionSettings hashcode

---

common/src/main/java/com/mx/path/core/common/configuration/package-info.java
common/src/main/java/com/mx/path/core/common/reflection/Fields.java
common/src/test/groovy/com/mx/path/core/common/reflection/FieldsTest.groovy

This adds support for regular expressions in the configuration binder. Can declare the field as a Pattern and the string will be parsed into the Pattern.

feat: add support for regex pattern configuration binding

---

common/src/main/java/com/mx/path/core/common/reflection/Fields.java
common/src/test/groovy/com/mx/path/core/common/reflection/FieldsTest.groovy

Adding support for Short, Byte, and Char configuration binding.

Support Short, Byte, and Char types in configuration binding

---

build.gradle
gateway/src/main/java/com/mx/path/gateway/accessor/Accessor.java
gateway/src/main/java/com/mx/path/gateway/configuration/AccessorConstructionContext.java
gateway/src/test/groovy/com/mx/path/gateway/configuration/AccessorConstructionContextTest.groovy
gateway/src/test/java/com/mx/testing/AccountAccessorNoConfigImpl.java
gateway/src/test/java/com/mx/testing/TransactionAccessorNoConfigImpl.java
gateway/src/test/java/com/mx/testing/accessors/AccountBaseAccessor.java
gateway/src/test/java/com/mx/testing/accessors/TransactionBaseAccessor.java
gateway/src/test/java/com/mx/testing/binding/AccessorWithNoConfigWithBoundConfiguration.java
gateway/src/test/java/com/mx/testing/binding/AccessorWithNoConfigWithBoundConnections.java

https://gitlab.mx.com/mx/experiences/mobile-core/core-issues/-/issues/177
This removes the requirement from Accessors to have an AccessorConfiguration typed parameter in their constructor.

feat: removing requirement for AccessorConfiguration parameter

---

common/src/main/java/com/mx/path/core/common/configuration/package-info.java
common/src/main/java/com/mx/path/core/common/reflection/Fields.java
common/src/test/groovy/com/mx/path/core/common/reflection/FieldsTest.groovy

Add support for zoneId configuration value binding.

feat: add support for ZoneId binding

---

common/src/main/java/com/mx/path/core/common/collection/MultiValueMap.java
common/src/main/java/com/mx/path/core/common/collection/SingleValueMap.java
common/src/test/groovy/com/mx/path/core/common/collection/MultiValueMapTest.groovy
common/src/test/groovy/com/mx/path/core/common/collection/SingleValueMapTest.groovy

Adds the slice convenience method to SingleValueMap and MultiValueMap. Extracts a new map containing only the key/values matching the provided Pattern.

feat: add slice convenience method to maps

---

common/src/main/java/com/mx/path/core/common/reflection/Fields.java
gateway/src/main/java/com/mx/path/gateway/configuration/AccessorConstructionContext.java
gateway/src/main/java/com/mx/path/gateway/configuration/ConfigurationBinder.java
gateway/src/test/groovy/com/mx/path/gateway/configuration/ConfigurationBinderTest.groovy
gateway/src/test/java/com/mx/testing/binding/BasicConfigurationObj.java

Allow configuration lists to include coerced types (e.g. Pattern, ZoneId)

feat(configuration): allow coerced types in arrays

---

context/src/main/java/com/mx/path/core/context/Session.java
context/src/test/groovy/com/mx/path/core/context/SessionTest.groovy

This solution has major drawbacks but restores the ability to set the session expiration. This ability was lost during SDK reorganization.
Main drawback: the expiration cannot be scopes(can't be set by client or connection).
Another solution will be needed to make this fully configurable.

fix: allow setting of default session expiration

---

build.gradle
context/src/main/java/com/mx/path/core/context/store/SessionRepositoryImpl.java
context/src/test/groovy/com/mx/path/core/context/store/SessionRepositoryImplTest.groovy

Currently, on logout (session.delete), keys set in the SessionStore are not removed (only the primary session key). This changes SessionRepositoryImpl by adding a tracking set for all keys set using `Session.current().put()|sput()|putObj()|sputObj()`. On session delete, all of the keys in the set will be removed from the store along with the primary session object.
Example of `redis-cli MONITOR` logs:
```
1692118020.292167 [0 127.0.0.1:54994] "EXPIRE" "b40ca95b-3f5d-4fa3-82c5-c005fe2e08f9:Session.huge" "58"
1692118020.329654 [0 127.0.0.1:54994] "SET" "b40ca95b-3f5d-4fa3-82c5-c005fe2e08f9" "{\"clientId\":\"test\",\"expiresAt\":1692118078,\"deviceId\":\"device1\",\"id\":\"b40ca95b-3f5d-4fa3-82c5-c005fe2e08f9\",\"sessionState\":\"AUTHENTICATED\",\"startedAt\":{\"time\":{\"hour\":16,\"minute\" …
```

feat(session): track keys saved to session store and DEL on logout

---

common/src/main/java/com/mx/path/core/common/serialization/LocalDateTimeDeserializer.java
common/src/main/java/com/mx/path/core/common/serialization/LocalDateTimeJava8.java
common/src/main/java/com/mx/path/core/common/serialization/LocalDateTimeTypeAdapter.java
common/src/main/java/com/mx/path/core/common/serialization/LocalDateTypeAdapter.java
common/src/main/java/com/mx/path/core/common/serialization/SystemTypeAdapterFactory.java
common/src/test/groovy/com/mx/path/core/common/serialization/LocalDateTimeTypeAdapterTest.groovy
common/src/test/groovy/com/mx/path/core/common/serialization/SystemTypeAdapterFactoryTest.groovy

Implement LocalDateTime type adapter and mark LocalDateTimeDeserializer as deprecated.

feat(serialization): add LocalDateTimeTypeAdapter

---

gateway/src/main/java/com/mx/path/gateway/util/UpstreamLogger.java

Turns out we weren't masking the request URIs

fix: masking request URIs in UpstreamLogger

---

common/src/main/java/com/mx/path/core/common/accessor/API.java
gateway-generator/src/main/java/com/mx/path/api/ApiMethod.java
gateway-generator/src/main/java/com/mx/path/api/GatewayGenerator.java
gateway-generator/src/test/groovy/com/mx/path/api/ApiMethodTest.groovy
test-models/src/main/java/com/mx/testing/accessors/AccountBaseAccessor.java
test-models/src/main/java/com/mx/testing/models/v20240101/Account.java

This fixes a problem that occurs when there are 2 classes with the same name in different packages. Brings the logic out of ApiMethod and into GatewayGenerator so that JavaPoet can be used to determine the right package imports.
Also, adds version attribute to the `@API` annotation.

fix: correct ambiguous model namespaing in generated gateways

---

gateway-generator/src/main/java/com/mx/path/api/GatewayGenerator.java
test-gateways/src/test/groovy/com/mx/gateway/GatewayMethodSpec.groovy
test-gateways/src/test/java/com/mx/testing/AccountAccessorImpl.java
test-models/src/main/java/com/mx/testing/accessors/AccountBaseAccessor.java

The cast uses the simple name of the class. This won't work if there are multiple classes with the same name. Needs to use the canonical name. Adding some tests to check the internals of the generated gateway methods.

fix: fix ambiguous cast of incoming object in gateway methods

---

common/src/main/java/com/mx/path/core/common/accessor/AccessorMethodNotImplementedException.java
common/src/main/java/com/mx/path/core/common/accessor/RequestPayloadException.java
common/src/main/java/com/mx/path/core/common/accessor/ResponsePayloadException.java
common/src/main/java/com/mx/path/core/common/connect/CircuitOpenException.java
common/src/main/java/com/mx/path/core/common/connect/TooManyRequestsException.java
common/src/main/java/com/mx/path/core/common/exception/PathRequestException.java
common/src/main/java/com/mx/path/core/common/facility/FacilityException.java
common/src/main/java/com/mx/path/core/common/gateway/BehaviorException.java
common/src/test/groovy/com/mx/path/core/common/exception/PathRequestExceptionTest.groovy

Adds a new flag to PathRequestException `internal` that indicates if the exception being thrown represents an internal error (as opposed to an upstream error). Setting this flag will add an additional header to the response so that the error can be handled appropriately by calling service.

feat: add new PathRequestException flag and header to indicate internal errors

---

common/src/main/java/com/mx/path/core/common/connect/AccessorConnectionSettings.java
common/src/main/java/com/mx/path/core/common/connect/ConnectionSettings.java
common/src/main/java/com/mx/path/core/common/connect/Request.java
common/src/test/groovy/com/mx/path/core/common/connect/RequestTest.groovy
http/src/main/java/com/mx/path/connect/http/HttpClientFilter.java

Adds ability to configure `connectTimeout` and `requestTimeout` in `AccessorConnectionSettings`.
If built Request already calls `withTimeOut`, `withTimeout` or `withConnectTimeout`, those values will be honored in place of these configured values.
If `withTimeOut` `withTimeout` or `withConnectTimeout` are not called and there is no configuration for the AccessorConnection, then the defaults will be used (30 seconds).
Fixes # MC-1709
No changes to APIs.
No breaking changes to consumer, this is a simple add-on that will allow more configurability for connection and request timeouts at the `AccessorConnectionSettings` level.

feat: add configurable ConnectTimeout and RequestTimeout

---

common/src/main/java/com/mx/path/core/common/connect/Request.java
common/src/test/groovy/com/mx/path/core/common/connect/RequestTest.groovy

Fixes # MC-1709
No outward changes
ConnectTimeout default dropped from 30 seconds to 5 seconds

fix: drop default connect timeout to 5 seconds

---

common/src/main/java/com/mx/path/core/common/messaging/MessageBrokerException.java
messaging/src/main/java/com/mx/path/connect/messaging/remote/RemoteCRUDModel.java
messaging/src/test/groovy/com/mx/path/connect/messaging/remote/RemoteCRUDModelTest.groovy

- Recreated Timeout Error: Stopped the NATs in local and executed `authenticateStart.http` to trigger the timeout error.
- Updated Exception Handling: Created a new custom exception class, MessageBrokerException, in path.core to enhance messageError.
- Test Class Adjustments**: Made corresponding updates to the related test classes.
- Local Testing: Successfully tested the NATs exception in `test-connector`, confirming that the internal error flag appears in the header.

internal error flag handled for nats timeout error

---

common/src/main/java/com/mx/path/core/common/accessor/AfterAccessorInitialize.java
gateway/src/main/java/com/mx/path/gateway/configuration/AccessorStackConfigurator.java
gateway/src/test/groovy/com/mx/path/gateway/configuration/AccessorStackConfiguratorTest.groovy
gateway/src/test/groovy/com/mx/path/gateway/configuration/ConfiguratorTest.groovy

Add hook method on Accessor which is called after class is built.
```java
public class MyAccessor extends Accessor {
// This method will be invoked after MyAccessor is initialized.
@AfterAccessorInitialize
static void afterInitialize() {
// Perform post-initialization tasks here
System.out.println("MyAccessor has been initialized!");
}
}
```

feat: add after initialize method on accessor

---

gateway/src/main/java/com/mx/path/gateway/accessor/AccessorConnectionBase.java

This will allow for advanced customization of the Request filter call
stack. Insertion, deletion, and reordering can be done. See javadoc for
example. Override is optional.

feat: add hook to AccessorConnectionBase that allows for call stack modifications

---

gateway/src/main/java/com/mx/path/gateway/util/UpstreamLogger.java

The logic around logging of request_method is backwards.

fix: logic error on request_method logging

---

gateway/src/main/java/com/mx/path/gateway/configuration/Configurator.java
gateway/src/test/groovy/com/mx/path/gateway/configuration/ConfiguratorTest.groovy

Facility defaults not being applied if there was no `facilities:` node in gateway.yaml. This fixes the logic to still apply defaults if no node is present. This bug will present itself when we start moving apps to use facility defaults.

fix: initialize facilities when facilities are empty

---

http/src/main/java/com/mx/path/connect/http/HttpClientFilter.java

Fixing external timeout issues with 531 instead 500 for better availability

Fixing external timeout issues with 531 instead 500 for better availability

---

gateway/src/test/groovy/com/mx/path/gateway/configuration/ConnectionBinderTest.groovy
gateway/src/test/groovy/com/mx/path/gateway/configuration/GatewayObjectConfiguratorTest.groovy
gateway/src/test/java/com/mx/testing/binding/BehaviorWithConfigurationAndConnection.java

Add test cases to `ConnectionBinder` and binding of `Connections` on gateway objects.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

feat: add tests to connection binding on gateway objects

---

common/src/main/java/com/mx/path/core/common/accessor/ResponsePayloadException.java
common/src/main/java/com/mx/path/core/common/accessor/UpstreamResponseError.java
common/src/main/java/com/mx/path/core/common/accessor/UpstreamResponseException.java
common/src/main/java/com/mx/path/core/common/accessor/UpstreamResponseProcessingException.java
common/src/main/java/com/mx/path/core/common/accessor/UpstreamResponseUnprocessableException.java
common/src/main/java/com/mx/path/core/common/accessor/UpstreamResponseValidationException.java
common/src/main/java/com/mx/path/core/common/accessor/UpstreamSystemUnavailable.java
common/src/main/java/com/mx/path/core/common/exception/PathRequestException.java
gateway/src/main/java/com/mx/path/gateway/util/SoapMarshaller.java

Add new sub-class of exceptions for upstream errors. These will help us better-categorize errors related to upstream system responses.
Also deprecating `ResponsePayloadException` since it is being replaced with the new, more specific exceptions.

feat: add upstream response exceptions

---

gateway/src/main/java/com/mx/path/gateway/util/UpstreamLogger.java

Remove unnecessary tab at the beginning of UpstreamLogger api_call_payload
None
None
Tested locally via SNAPSHOT versions, verified console output

fix: remove unnecessary tab from beginning of UpstreamLogger output
